import { useEffect, useState } from 'react';
import { Link, NavLink, Outlet } from 'react-router-dom';
import { Menu, ShoppingBag, X } from 'lucide-react';
import { useCart } from '../context/CartContext';

export default function Layout(){
 const {cart,remove,total,count,open,setOpen}=useStore(); const [menu,setMenu]=useState(false); const [scrolled,setScrolled]=useState(false);
 useEffect(()=>{const f=()=>setScrolled(scrollY>30);addEventListener('scroll',f);f();return()=>removeEventListener('scroll',f)},[]);
 return <><div className="noise"/><header className={`nav ${scrolled?'scrolled':''}`}><div className="nav-inner"><Link className="logo" to="/">DS</Link><nav className={`nav-links ${menu?'mobile-open':''}`}><NavLink to="/catalog" onClick={()=>setMenu(false)}>Shop</NavLink><NavLink to="/about" onClick={()=>setMenu(false)}>About</NavLink><NavLink to="/lookbook" onClick={()=>setMenu(false)}>Lookbook</NavLink><NavLink to="/contact" onClick={()=>setMenu(false)}>Contact</NavLink></nav><div className="nav-actions"><button className="icon-btn mobile-menu-btn" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X size={18}/>:<Menu size={18}/>}</button><button className="icon-btn" onClick={()=>setOpen(true)}><ShoppingBag size={17}/> Cart <span className="cart-count">{count}</span></button></div></div></header><main><Outlet/></main><footer className="footer"><div className="container footer-grid"><div><h3>After dark awaits</h3><p>Join the rebellion — step into the shadows and make your mark tonight.</p></div><form className="newsletter" onSubmit={e=>e.preventDefault()}><input type="email" placeholder="Email address"/><button>Join →</button></form></div><div className="container footer-bottom"><span>© 2026 Dark Society</span><div className="socials"><a href="#">Instagram</a><a href="https://www.tiktok.com/@darksociety.wear">TikTok</a><Link to="/contact">Contact</Link></div></div></footer><div className={`cart-backdrop ${open?'open':''}`} onClick={()=>setOpen(false)}/><aside className={`cart-drawer ${open?'open':''}`}><div className="cart-head"><strong>Cart</strong><button className="close" onClick={()=>setOpen(false)}>×</button></div><div className="cart-items">{cart.length?cart.map(i=><div className="cart-item" key={`${i.id}-${i.size}`}><img src={`/${i.img}`} alt={i.name}/><div><strong>{i.name}</strong><br/><span className="muted">Qty: {i.qty}{i.size?` · ${i.size}`:''}</span><br/>€{i.price.toFixed(2)}</div><button className="close" onClick={()=>remove(i.id,i.size)}>×</button></div>):<p className="muted">Cart is empty.</p>}</div><div className="cart-foot"><p>Total: <strong>€{total.toFixed(2)}</strong></p><Link className="btn block" to="/cart" onClick={()=>setOpen(false)}>Checkout UI</Link></div></aside></>
}
